### ISSUE TITLE
Is statsrelay v0.0.9 compatible with buckytools v0.4.2?

### ISSUE THREAD

**Issue by ritmas** [jjneely/statsrelay#28]
I have the following architecture in-place:
```
statsd metrics -> statsrelay -> x2 gostatsd -> x2 go-carbon
```

As far as I understood, `statsrelay` uses `fnv1a` hashing algorithm for hash ring, but [buckytools](https://github.com/jjneely/buckytools#tools) `inconsistent` command shows inconsistency with all supported (`carbon`, `fnv1a`, `jump_fnv1a`) algorithms.

```
$ statsrelay -p=8125 10.0.0.1:18125:node-1 10.0.0.2:18125:node-2

$ echo "foo.bar.bob:1|c" | nc -w1 -u 10.0.0.1 8125   <-- landed on node-2
$ echo "foo.bar.john:1|c" | nc -w1 -u 10.0.0.1 8125  <-- landed on node-1

$ buckyd -node 10.0.0.1 -hash fnv1a 10.0.0.1:2003=node-1 10.0.0.2:2003=node-2
$ buckyd -node 10.0.0.2 -hash fnv1a 10.0.0.1:2003=node-1 10.0.0.2:2003=node-2

$ bucky inconsistent -f | grep foo
2020/09/02 17:42:35 10.0.0.1:4242 returned 110656 metrics
2020/09/02 17:42:35 10.0.0.2:4242 returned 109531 metrics
2020/09/02 17:42:35 Hashing...
2020/09/02 17:42:35 Hashing time was: 0s
2020/09/02 17:42:35 36404 inconsistent metrics found on 10.0.0.1:4242
2020/09/02 17:42:35 35111 inconsistent metrics found on 10.0.0.2:4242
10.0.0.1:4242: stats.foo.bar.john
10.0.0.1:4242: stats_counts.foo.bar.john
```

**Comment by jjneely** [comment]
The statsrelay code works with the StatsD protocol.  Buckytools works with Graphite whisper time series on disk.  While StatsD data does become time series on disk, these are two different protocols.  Statsrelay is intended to spread load over a set of gostatsd daemons, but not control where time series get stored on disk by Graphite.

Looks like you have each Gostatsd daemon pointed at its own go-carbon daemon directly.  The intended setup is that the summary metrics from gostatsd as well as the other graphite style metrics are routed through a carbon-relay or carbon-c-relay.  That's the daemon that load balances via consistent hashing graphite metrics through the graphite cluster.  The consistent hashing methods that these relay daemons use is what Buckytools is intended to match.

**Comment by ritmas** [comment]
Yeah, the following flow did worked:
```
statsd metrics -> statsrelay -> gostatsd -> carbon-c-relay -> x2 go-carbon
```

`gostatsd` alone (removing `statsrelay`) didn't worked for me as server load has increased almost x2 and metrics on `carbon-c-relay` started dropping, which is weird. Perhaps some misconfiguration, which I didn't analyzed further.
